spring:
  threads:
    virtual:
      enabled: true
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}

backend:
  mqtt:
    host: ${BACKEND_MQTT_HOST}
    topic: ${BACKEND_MQTT_TOPIC}
  influx:
    host: ${BACKEND_INFLUX_HOST}
    token: ${BACKEND_INFLUX_TOKEN}
    bucket: ${BACKEND_INFLUX_BUCKET}
    org: ${BACKEND_INFLUX_ORG}
server:
  port: 12200

grpc:
  client:
    firebase-auth:
      address: ${GRPC_FIREBASE_INTEG_ADRES}
      negotiation-type: plaintext