spring:
  mqtt:
    enabled: true
    url: ${BACKEND_MQTT_HOST}
    client-id: ${BACKEND_MQTT_CLIENT_ID:spring-mqtt-scanner}
    topics:
      - "lockly/logs"
    default-qos: ${BACKEND_MQTT_DEFAULT_QOS:1}

    # username: ${BACKEND_MQTT_USERNAME}
    # password: ${BACKEND_MQTT_PASSWORD}
    clean-session: ${BACKEND_MQTT_CLEAN_SESSION:true}
    connection-timeout: ${BACKEND_MQTT_CONNECTION_TIMEOUT:15}
    keep-alive-interval: ${BACKEND_MQTT_KEEP_ALIVE_INTERVAL:30}
    automatic-reconnect: ${BACKEND_MQTT_AUTOMATIC_RECONNECT:true}

  threads:
    virtual:
      enabled: true

  application:
    name: backend

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

backend:
  influx:
    host: ${BACKEND_INFLUX_HOST}
    token: ${BACKEND_INFLUX_TOKEN}
    bucket: ${BACKEND_INFLUX_BUCKET}
    org: ${BACKEND_INFLUX_ORG}

server:
  port: 12200

grpc:
  client:
    firebase-auth:
      address: ${GRPC_FIREBASE_INTEG_ADRES}
      negotiation-type: plaintext

logging:
  level:
    com.kowallo.spring: DEBUG
    org.springframework.integration.mqtt: DEBUG