CREATE TABLE users (
                       firebase_id VARCHAR(128) NOT NULL,
                       email VARCHAR(255),
                       CONSTRAINT pk_users PRIMARY KEY (firebase_id),
                       CONSTRAINT uc_users_email UNIQUE (email),
                       CONSTRAINT uc_users_firebase_id UNIQUE (firebase_id)
);

CREATE TABLE devices (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         device_id VARCHAR(255) NOT NULL,
                         blocked BOOLEAN DEFAULT FALSE NOT NULL,
                         user_firebase_id VARCHAR(128),
                         CONSTRAINT pk_devices PRIMARY KEY (id),
                         CONSTRAINT uc_devices_device_id UNIQUE (device_id),
                         CONSTRAINT fk_devices_on_user FOREIGN KEY (user_firebase_id) REFERENCES users (firebase_id)
);

CREATE INDEX idx_device_user_firebase_id ON devices (user_firebase_id);
CREATE INDEX idx_device_user_email ON users (email);