syntax = "proto3";

package com.example.backend.common.proto;

option java_multiple_files = true;
option java_package = "com.example.backend.common.auth";
option java_outer_classname = "AuthProto";

service AuthService {
  rpc VerifyToken (VerifyTokenRequest) returns (AuthTokenResponse);
}

message VerifyTokenRequest {
  string token = 1;
}

message AuthTokenResponse {
  string uid = 1;
  string email = 2;
  string name = 3;
  string photoUrl = 4;
  string issuer = 5;
  map<string, string> allClaims = 6;
}