name: iot-application

services:
  mqtt-broker:
    image: eclipse-mosquitto:${MOSQUITTO_VERSION}
    container_name: iot_mqtt_broker
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      # Montujemy plik konfiguracyjny (wymagane w Mosquitto 2.0+)
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      # Wolumeny na dane (trwałość wiadomości z QoS 1 i 2) oraz logi
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped
    networks:
      - app_network

  influxdb:
    container_name: iot_influxdb
    image: 'influxdb:2.7'
    ports:
      - '${INFLUX_DB_PORT}:8086'
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    networks:
      - app_network
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}

volumes:
  mosquitto_data:
  mosquitto_log:
  influx_data:
  influx_config:
  explorer_db:
  explorer_config:

networks:
  app_network:
    external: true
    name: ${APP_NETWORK_NAME}