server:
  port: 12100
spring:
  application:
    name: firebase-integration-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
firebase:
  key:
    path: ${FIREBASE_KEY_PATH}
