spring:
  application:
    name: backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BACKEND_ISSUER_URI}
          jwk-set-uri: ${BACKEND_JWK_SET_URI}

backend:
  mqtt:
    host: ${BACKEND_MQTT_HOST}
    topic: ${BACKEND_MQTT_TOPIC}
  influx:
    host: ${BACKEND_INFLUX_HOST}
    token: ${BACKEND_INFLUX_TOKEN}
    database: ${BACKEND_INFLUX_DATABASE}